# Generated by Django 5.0.6 on 2024-06-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('task_details', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('asign_date', models.DateField()),
            ],
        ),
    ]
