# Generated by Django 5.0.6 on 2024-06-01 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmodel',
            old_name='asign_date',
            new_name='assign_date',
        ),
    ]
